#!/bin/sh
### BEGIN INIT INFO
# Provides:          alarm
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Starts the alarm program.
# Description:       Starts the alarm program.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/home/pi/alarm
. /lib/init/vars.sh
PIDFILE=/var/run/gpio_button.pid

do_start () {
	# TODO: Start the alarm by running these commands

}

do_status () {
	# TODO: Add some indication of status here.
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# Add operation to kill the alarm here.
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: alarm [start|stop|status]" >&2
	exit 3
	;;
esac

:
